zn:
    commands:
        Script: [ex]
        Migrations: [migration, migrations, apply, redo]
        Stationary: [create, migration, app, instance, pub, update, stationary, config]
        Edit: [edit]
